- id: '1605130829896'
  alias: Schlafzimmer Szene  ON 22:00, random 1-30, not_home
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: not_home
  action:
  - wait_template: '{{ ''00:%02i:00''%range(01,30) | random }}'
  - scene: scene.hue_schlafzimmer_on_ambient
  mode: single
- id: '1605131875883'
  alias: Schlafzimmer Szene OFF 23:30, random 1-20, not_home
  description: ''
  trigger:
  - platform: time
    at: '23:30:00'
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: not_home
  action:
  - wait_template: '{{ ''00:%02i:00''%range(01,20) | random }}'
  - type: turn_off
    device_id: 0dd0ce477d4f719fd4fc8341b067bc85
    entity_id: light.schlafzimmer
    domain: light
  - type: turn_off
    device_id: 44c495113e18e26db13a2f4bdc5442a4
    entity_id: light.schlafzimmer_pia
    domain: light
  - type: turn_off
    device_id: bcf481a9e79122849c323a61b91105d9
    entity_id: light.schlafzimmer_stephan
    domain: light
  mode: single
- id: '1605216723225'
  alias: Wohnzimmer Szene  ON 05:30:00, home
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - scene: scene.hue_wohnzimmer_on_ambient
  mode: single
- id: '1605216797509'
  alias: Wohnzimmer Szene OFF Sunrise plus 1 hour
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 01:00:00
  condition: []
  action:
  - scene: scene.hue_wohnzimmer_off
  mode: single
- id: '1605247431207'
  alias: Wohnzimmer Szene  ON Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - scene: scene.hue_wohnzimmer_on_ambient
  mode: single
- id: '1605247871692'
  alias: Wohnung Hue OFF, 01:00, random 1-30, not_home
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: not_home
  action:
  - wait_template: '{{ ''00:%02i:00''%range(01,30) | random }}'
  - scene: scene.hue_wohnzimmer_off
  - scene: scene.hue_buro_off
  - scene: scene.hue_schlafzimmer_off
  - type: turn_off
    device_id: dc41bd82f147d78bd4d07285cf947d9d
    entity_id: light.gang
    domain: light
  mode: single
- id: '1605249083791'
  alias: Büro Szene ON Sunset, home
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - scene: scene.hue_buro_on_ambient
  mode: single
- id: '1605249667376'
  alias: Büro Szene ON Sunset, not_home (Simulation)
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: not_home
  action:
  - repeat:
      while:
      - condition: or
        conditions:
        - condition: sun
          after: sunset
        - condition: time
          before: 01:00:00
      sequence:
      - wait_template: 'false'
        timeout: '{{ ''00:%02i:00''%range(01,10) | random }}'
        continue_on_timeout: true
      - scene: scene.hue_buro_on_ambient
      - wait_template: 'false'
        timeout: '{{ ''00:%02i:00''%range(10,20) | random }}'
        continue_on_timeout: true
      - scene: scene.hue_buro_off
  mode: single
- id: '1613892335068'
  alias: Wohnung Kameras ON (P,W,R) (home -> not_home)
  description: ''
  trigger:
  - platform: state
    entity_id: group.awesome_people
    from: home
    to: not_home
  condition: []
  action:
  - scene: scene.mystrom_presence_on
  - scene: scene.mystrom_welcome_on
  - scene: scene.mystrom_reolink_on
  mode: single
- id: '1613892576072'
  alias: Wohnung Kameras ON (P,W,R) (home, sleep co2 > 1000)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.netatmo_steffs_home_living_sleep_co2
    above: '1000'
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - scene: scene.mystrom_presence_on
  - scene: scene.mystrom_welcome_on
  - scene: scene.mystrom_reolink_on
  mode: single
- id: '1613892789706'
  alias: Wohnung Kameras OFF (P,W) (not_home -> home, vor sunset - 60 Min)
  description: ''
  trigger:
  - platform: state
    entity_id: group.awesome_people
    from: not_home
    to: home
  condition:
  - condition: sun
    before: sunset
    before_offset: -01:00:00
  action:
  - scene: scene.mystrom_presence_off
  - scene: scene.mystrom_welcome_off
  mode: single
- id: '1613894596079'
  alias: Wohnung Kameras ON (P,W) (home, sunset - 45 min)
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - scene: scene.mystrom_presence_on
  - scene: scene.mystrom_welcome_on
  mode: single
- id: '1613895437670'
  alias: Wohnung Kameras OFF (P,W) (home, sunrise + 45 min)
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:45:00
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - scene: scene.mystrom_presence_off
  - scene: scene.mystrom_welcome_off
  mode: single
- id: '1613895565229'
  alias: Wohnung Kameras OFF (R) (home, sunrise + 45 Min) --- TODO ---
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:45:00
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - scene: scene.mystrom_reolink_off
  mode: single
- id: '1614287759637'
  alias: 'Wohnung Kameras OFF (R) (not_home -> home) '
  description: ''
  trigger:
  - platform: state
    entity_id: group.awesome_people
    from: not_home
    to: home
  condition: []
  action:
  - scene: scene.mystrom_reolink_off
  mode: single
- id: '1616048845700'
  alias: Bad Hue Light on Motion Webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: bad_light_on_motion
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: sun
          after: sunrise
        - condition: sun
          before: sunset
      sequence:
      - scene: scene.hue_bad_on_full_white
    default:
    - scene: scene.hue_bad_on_ambient
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - scene: scene.hue_bad_off
  mode: restart
- id: '1616050267437'
  alias: Dusche Hue Light on Motion Webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: dusche_light_on_motion
  condition: []
  action:
  - choose:
    - conditions:
      - condition: sun
        after: sunset
      sequence:
      - scene: scene.hue_dusche_on_full
    - conditions:
      - condition: sun
        before: sunrise
      sequence:
      - scene: scene.hue_dusche_on_ambient
    default: []
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - scene: scene.hue_dusche_off
  mode: restart
- id: '1616071228508'
  alias: Dusche Licht OFF (no motion)
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_deko_usm_motion
    to: 'off'
    for: 00:10:00
  condition: []
  action:
  - service: script.dingz_light_level_generic
    data:
      dimmer: 2
      enum: 'off'
      brightness: 0
      ip: 192.168.1.196
  - service: script.dingz_light_level_generic
    data:
      dimmer: 3
      enum: 'off'
      brightness: 0
      ip: 192.168.1.196
  mode: single
- id: '1616393998146'
  alias: Gang Hue Stufe 001 bis 006, abhängig Temperatur, @home
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: /5
    seconds: '0'
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: group.awesome_people
        state: home
      sequence:
      - choose:
        - conditions:
          - condition: numeric_state
            entity_id: sensor.netatmo_steffs_home_living_outdoor_temperature
            below: '-5'
          sequence:
          - scene: scene.hue_gang_stufe_001_violett_minus_6_und_kalter
        - conditions:
          - condition: numeric_state
            entity_id: sensor.netatmo_steffs_home_living_outdoor_temperature
            below: '3'
          sequence:
          - scene: scene.hue_gang_stufe_002_hellblau_minus_5_bis_2_grad
        - conditions:
          - condition: numeric_state
            entity_id: sensor.netatmo_steffs_home_living_outdoor_temperature
            below: '11'
          sequence:
          - scene: scene.hue_gang_stufe_003_grun_3_bis_10_grad
        - conditions:
          - condition: numeric_state
            entity_id: sensor.netatmo_steffs_home_living_outdoor_temperature
            below: '21'
          sequence:
          - scene: scene.hue_gang_stufe_004_gelb_11_bis_20_grad
        - conditions:
          - condition: numeric_state
            entity_id: sensor.netatmo_steffs_home_living_outdoor_temperature
            below: '31'
          sequence:
          - scene: scene.hue_gang_stufe_005_orange_21_bis_30_grad
        default:
        - scene: scene.hue_gang_stufe_006_rot_31_grad_und_warmer
    default:
    - type: turn_off
      device_id: dc41bd82f147d78bd4d07285cf947d9d
      entity_id: light.gang
      domain: light
  mode: single
- id: '1616394722797'
  alias: Gang Schrank Lüfter ON-OFF, abhängig Temperatur
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: '0'
    seconds: '0'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.mystrom_schrank_lufter_temperature
        above: '32'
      sequence:
      - scene: scene.mystrom_schrank_lufter_on
    - conditions:
      - condition: numeric_state
        entity_id: sensor.mystrom_schrank_lufter_temperature
        below: '28'
      sequence:
      - scene: scene.mystrom_schrank_lufter_off
    default: []
  mode: single
- id: '1616394930906'
  alias: Keller Entfeuchter ON-OFF, abhängig Luftfeuchtigkeit
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: '0'
    seconds: '0'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.netatmo_steffs_home_keller_humidity
        above: '59'
      sequence:
      - scene: scene.mystrom_entfeuchter_on
    - conditions:
      - condition: numeric_state
        entity_id: sensor.netatmo_steffs_home_keller_humidity
        below: '56'
      sequence:
      - scene: scene.mystrom_entfeuchter_off
    default: []
  mode: single
- id: '1616563856843'
  alias: Test Simulation
  description: ''
  trigger:
  - platform: time
    at: 07:50:00
  condition:
  - condition: state
    entity_id: group.awesome_people
    state: home
  action:
  - repeat:
      while:
      - condition: and
        conditions:
        - condition: sun
          after: sunrise
        - condition: sun
          before: sunset
      sequence:
      - wait_template: 'false'
        timeout: '{{ ''00:%02i:00''%range(01,03) | random }}'
        continue_on_timeout: true
      - scene: scene.hue_wohnzimmer_on_ambient
      - wait_template: 'false'
        continue_on_timeout: true
        timeout: '{{ ''00:%02i:00''%range(01,03) | random }}'
      - scene: scene.hue_wohnzimmer_off
  mode: single
